parameters:
#    lou_test.example.class: Lou\TestBundle\Example

services:
#    lou_test.example:
#        class: %lou_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
